http:
  address: ${HTTP_ADDRESS:0.0.0.0:4195}

input:
  cassandra:
    addresses:
    - ${CASSANDRA_ADDRESS:localhost}:${CASSANDRA_PORT:9042}
    tls:
      enabled: ${CASSANDRA_TLS_ENABLED:true}
      skip_cert_verify: ${CASSANDRA_TLS_SKIP_CERT_VERIFY:true}
      enable_renegotiation: ${CASSANDRA_TLS_ENABLE_RENEGOTIATION:true}
    password_authenticator:
      enabled: ${CASSANDRA_PASSWORD_AUTHENTICATOR_ENABLED:true}
      username: ${CASSANDRA_USER}
      password: ${CASSANDRA_PASSWORD}
    disable_initial_host_lookup: ${CASSANDRA_DISABLE_INITIAL_HOST_LOOKUP:true}
    keyspace: ${CASSANDRA_KEYSPACE:my_keyspace}
    query: >
      ${CASSANDRA_QUERY:select * from my_table}
    page_size: ${CASSANDRA_PAGE_SIZE:100}
    timeout: ${CASSANDRA_TIMEOUT:1s}
    max_in_flight: ${CASSANDRA_MAX_IN_FLIGHT:1}
    batching:
      count: ${CASSANDRA_OUTPUT_BATCH_COUNT:0}
      byte_size: ${CASSANDRA_OUTPUT_BATCH_BYTE_SIZE:0}
      period: ${CASSANDRA_OUTPUT_BATCH_PERIOD:""}

pipeline:
  processors:
  - log:
      level: INFO
      message: "cassandra row"
      fields:
        row: '${! json() }'

output:
  file:
    path: "${FILE_OUTPUT_PATH:/tmp/out.jsonl}"
    codec: lines
